global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['nodejs-app:3000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
